### ISSUE TITLE
liveview support ?

### ISSUE THREAD

**Issue by SquirrelMobile** [appcelerator/atom-appcelerator-titanium#58]
I don't see how to active liveview when i build ?

**Comment by m1ga** [comment]
In my opinion I think it is difficult to add a button yet because it won't work if you don't have the liveview service installed. And the npm package is only included in Studio at the moment. 
So if you JUST use Atom without ever installed Studio it won't work and might be misleading. 
You can install it (the npm package is inside Studio and you can install it via `npm install -g liveview-folder/` and the run `liveview-install`. After that you can use it in CLI with `--liveview`. 

One way would be to check for the existence of `liveview` first and then enable a button to add the parameter to the build command. This way you could also check if you use a hyperloop project and then disable it again.

**Comment by hansemannn** [comment]
LiveView will be moved out of the CLI in the future (not binding on exact dates), which will allow it to be used both by Studio, the CLI (`--liveview`) or Atom (via a toggle button).

**Comment by genocsb** [comment]
Waiting the toggle button, I hardcode it and constantly build with liveview 
add args in buildCommand 
file /.atom/packages/appcelerator-titanium/lib/index.js
function runBuildCommand()
             if (buildCommand === 'run') {
			args = [
				'--platform', platform,
				'--project-dir', atom.project.getPaths()[0],
				'--target', targetType,
				'--log-level', logLevel,
				"--liveview"
			];

**Comment by gilbertoLopez** [comment]
Following the response from @genocsb , an easy way to implement it is with a confirmation popup:

`                if (buildCommand === 'run') { `
`                        < .... >`
`                        if (targetType !== 'ws-local') {`
`                                args.push('--device-id', target);`
`                        }`
**`                      if (confirm("Enable liveview?")) {`**
 **`args.push('--liveview');`**
**`                      }`**

**Comment by m1ga** [comment]
While this will enable liveview it will be a problem (bad user experience) for new users or users that don't use Appc Studio at all since they don't have liveview. So you have to check for liveview first to enable this option at all. Otherwise people will try to use it and complain it is not working. So once it is available as a public npm module it would be nice to have as a switch!
